source 'https://github.com/CocoaPods/Specs.git'

source 'https://gitee.com/cuiyu8580/CYPodspec.git'



platform :ios, '9.0'

use_frameworks!
target 'ELWeChatDylib' do

pod 'YYModel'

pod 'CYMHUD'


end
